image: ubuntu:bionic

stages:
  - build
  - test

before_script:
  - apt-get -qq update && apt-get -qq install -y software-properties-common
  - add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - apt-get -qq update && apt-get -qq install -y git g++-9 lcov cmake make python python-pip doxygen
  - pip install --upgrade pip && pip install --user cogapp conan cmake
  - g++-9 --version

cache:
  paths:
    - build

build:
  stage: build
  script:
    - mkdir build && cd build
    - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake . -Bbuild -DENABLE_COVERAGE:BOOL=1 ..
    - cmake --build build -- -j 2
  only:
    - master
    - develop

test:
  stage: test
  script:
    - ctest -j2
    - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov