image: bionic

stages:
  - build
  - test

before_script:
  - apt-get -qq update && apt-get -qq install -y python gcc g++ cmake make doxygen
  - pip install --user cogapp conan cmake

cache:
  paths:
    - build

build:
  stage: build
  script:
    - mkdir build && cd build
    - CXX=/usr/bin/g++ CC=/usr/bin/gcc cmake . -Bbuild -DENABLE_COVERAGE:BOOL=1 ..
    - cmake --build build -- -j 2
  only:
    - master
    - develop

test:
  stage: test
  script:
    - ctest -j2
    - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5