dist: xenial
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - doxygen

install:
  - pip install --user cogapp conan cmake


script:
  - ls /usr/bin/gcc*
  - ls /usr/bin/g++*
  - g++-9 --version
  - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake -DENABLE_COVERAGE:BOOL=1 -DBUILD_DESKTOP_APP:BOOL=0 -DBUILD_TESTS:BOOL=1 . 
  - cmake --build . -- -j2 
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-9
