dist: bionic
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - doxygen

install:
  - pip install --user cogapp conan cmake


script:
  - mkdir build && cd build
  - CXX=/usr/bin/g++ CC=/usr/bin/gcc cmake . -Bbuild -DENABLE_COVERAGE:BOOL=1 ..
  - cmake --build build -- -j 2
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-9
