dist: bionic
sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - doxygen

install:
  - pip install --upgrade pip
  - pip install --user cogapp conan cmake


script:
  - g++ --version
  - mkdir build && cd build
  - CXX=/usr/bin/g++ CC=/usr/bin/gcc cmake . -Bbuild -DENABLE_COVERAGE:BOOL=1 ..
  - cmake --build build -- -j 2
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-9
